[build]
  command = "npm run build"
  publish = "dist"

[env]
  [env.production]
    VITE_API_URL = "https://interview-coach-backend-6git.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
